version: "2"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  logstash_csv:
    image: docker.elastic.co/logstash/logstash:5.6.3
    restart: always
    ports:
      - "5044:5044"    
    links:
      - elasticsearch:elasticsearch    
    volumes:
      - ./csv/pipeline/:/usr/share/logstash/pipeline/
      - ./csv/injest:/injest
    environment:
      - XPACK_MONITORING_ENABLED=false
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.3
    restart: always
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
